version: '3.8'

services:
  # api:
  #   build: .
  #     context: .
  #     dockerfile: ./endpoint/Dockerfile
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - mongo
  #   environment:
  #     - MONGO_URL=mongodb://mongo:27017
  #   networks:
  #     - mongo-network
  #   tty: true


  mongo:
    image: mongo:7.0.1
    container_name: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - mongo-network

  mongo-expless:
    image: mongo-express:1.0.0-alpha
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      # - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - mongo-network
    depends_on:
      - mongo

networks:
  mongo-network:
    driver: bridge

volumes:
  mongodb_data:
